Resources:
    Route53HealthCheck:
        Type: "AWS::Route53::HealthCheck"
        Properties:
            HealthCheckConfig:
                Port: 443
                Type: HTTPS
                ResourcePath: "/health"
                FullyQualifiedDomainName: ${self:custom.domainNameRegional}
                RequestInterval: 30
                FailureThreshold: 1
            HealthCheckTags:
                - Key: Name
                  Value: ${self:service}-${self:provider.region}
